# syntax=docker/dockerfile:1

FROM registry.redhat.io/ansible-automation-platform-25/ee-minimal-rhel9:latest

LABEL maintainer="Louis Gordner"
LABEL summary="Ansible Automation Platform EE with developer tooling"
LABEL description="Extends the minimal AAP 2.5 execution environment with ansible-dev-tools, ansible-lint, and ansible-navigator preinstalled while keeping ansible-core 2.16.14."

ENV PIP_NO_CACHE_DIR=1 \
    PIP_ROOT_USER_ACTION=ignore \
    PIP_BREAK_SYSTEM_PACKAGES=1 \
    ANSIBLE_STDOUT_CALLBACK=yaml \
    ANSIBLE_NAVIGATOR_CONFIG=/projects/ansible-navigator.yml

USER root

RUN microdnf install -y bash diffutils git git-lfs iproute jq less lsof man nano procps \
    perl-Digest-SHA net-tools openssh-clients rsync socat sudo time vim wget zip ansible-lint && \
    microdnf clean all

RUN python3 -m pip install --upgrade pip

# Remove rpm-managed packages that block pip upgrades
# RUN for pkg in python3.11-platformdirs python3.11-packaging python3.11-filelock; do \
#       rpm -q "${pkg}" && rpm -e --nodeps "${pkg}" || true; \
#     done

RUN echo 'ansible-core==2.16.14' > /tmp/pip-constraints.txt \
    && python3 -m pip install --no-cache-dir --upgrade \
        --constraint /tmp/pip-constraints.txt \
        'ansible-sign[ansible-core]' \
        'molecule[ansible-core]' \
        'pytest-ansible[ansible-core]' \
        'ansible-navigator[ansible-core]' \
    && rm -f /tmp/pip-constraints.txt

RUN ansible --version \
    && ansible-lint --version \
    && ansible-navigator --version

WORKDIR /projects
CMD ["/bin/bash"]
